Repository TeamDATEROAD/DATEROAD-SERVER, pull requests merged in 2024-07, with the labels that each got.

#4 [SETTING] Swagger 기본세팅 - #2
  build.gradle
  dateroad-api/build.gradle
  dateroad-api/src/main/java/org/dateroad/config/SwaggerConfig.java
Labels: setting, 성준

#7 [SETTING] 공통 클래스 & 예외 핸들링 클래스 세팅 - #3
  dateroad-api/src/main/java/org/dateroad/common/ApiResponseUtil.java
  dateroad-api/src/main/java/org/dateroad/common/FailureResponse.java
  dateroad-api/src/main/java/org/dateroad/common/GlobalExceptionHandler.java
  dateroad-api/src/main/java/org/dateroad/common/SuccessResponse.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
  dateroad-common/src/main/java/org/dateroad/code/SuccessCode.java
  dateroad-common/src/main/java/org/dateroad/exception/ConflictException.java
  dateroad-common/src/main/java/org/dateroad/exception/DateRoadException.java
  dateroad-common/src/main/java/org/dateroad/exception/EntityNotFoundException.java
  dateroad-common/src/main/java/org/dateroad/exception/InvalidValueException.java
  dateroad-common/src/main/java/org/dateroad/exception/UnauthorizedException.java
Labels: feat, setting, 정원

#10 [FEAT] Entity 클래스 매핑 - #6
  dateroad-domain/build.gradle
  dateroad-domain/src/main/java/org/dateroad/advertisement/domain/Advertisment.java
  dateroad-domain/src/main/java/org/dateroad/common/BaseTimeEntity.java
  dateroad-domain/src/main/java/org/dateroad/config/JpaConfig.java
  dateroad-domain/src/main/java/org/dateroad/date/domain/Course.java
  dateroad-domain/src/main/java/org/dateroad/date/domain/Date.java
  dateroad-domain/src/main/java/org/dateroad/date/domain/DateBase.java
  dateroad-domain/src/main/java/org/dateroad/date/domain/DateType.java
  dateroad-domain/src/main/java/org/dateroad/dateAccess/domain/DateAccess.java
  dateroad-domain/src/main/java/org/dateroad/image/domain/Image.java
  dateroad-domain/src/main/java/org/dateroad/like/domain/Like.java
  dateroad-domain/src/main/java/org/dateroad/place/domain/CoursePlace.java
  dateroad-domain/src/main/java/org/dateroad/place/domain/DatePlace.java
  dateroad-domain/src/main/java/org/dateroad/place/domain/Place.java
  dateroad-domain/src/main/java/org/dateroad/point/domain/Point.java
  dateroad-domain/src/main/java/org/dateroad/point/domain/TransactionType.java
  dateroad-domain/src/main/java/org/dateroad/tag/domain/CourseTag.java
  dateroad-domain/src/main/java/org/dateroad/tag/domain/DateTag.java
  dateroad-domain/src/main/java/org/dateroad/tag/domain/DateTagType.java
  dateroad-domain/src/main/java/org/dateroad/tag/domain/UserTag.java
  dateroad-domain/src/main/java/org/dateroad/user/domain/Platform.java
  dateroad-domain/src/main/java/org/dateroad/user/domain/User.java
Labels: feat, refactor, setting, 기훈

#9 [SETTING] Spring Security & JWT 세팅 - #5
  dateroad-api/build.gradle
  dateroad-api/src/main/java/org/dateroad/DateroadApplication.java
  dateroad-api/src/main/java/org/dateroad/auth/config/SecurityConfig.java
  dateroad-api/src/main/java/org/dateroad/auth/exception/ExceptionHandlerFilter.java
  dateroad-api/src/main/java/org/dateroad/auth/exception/JwtAuthenticationEntryPoint.java
  dateroad-api/src/main/java/org/dateroad/auth/filter/JwtAuthenticationFilter.java
  dateroad-api/src/main/java/org/dateroad/auth/filter/TokenAuthentication.java
  dateroad-api/src/main/java/org/dateroad/auth/jwt/JwtGenerator.java
  dateroad-api/src/main/java/org/dateroad/auth/jwt/JwtProperties.java
  dateroad-api/src/main/java/org/dateroad/auth/jwt/JwtProvider.java
  dateroad-api/src/main/java/org/dateroad/auth/jwt/JwtValidator.java
  dateroad-api/src/main/java/org/dateroad/auth/jwt/KeyProvider.java
  dateroad-api/src/main/java/org/dateroad/auth/jwt/Token.java
  dateroad-api/src/main/java/org/dateroad/auth/jwt/TokenType.java
  dateroad-api/src/main/java/org/dateroad/common/Constants.java
  dateroad-api/src/main/java/org/dateroad/config/ObjectMapperConfig.java
  dateroad-api/src/main/java/org/dateroad/config/SwaggerConfig.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
Labels: feat, setting, 성준

#14 [FIX] healthCheck security filter 이슈 해결 - #12
  dateroad-api/src/main/java/org/dateroad/auth/config/SecurityConfig.java
Labels: fix, 성준

#11 [REFACT] 성공 응답 구조 변경 - #8
  dateroad-api/src/main/java/org/dateroad/common/ApiResponseUtil.java
  dateroad-api/src/main/java/org/dateroad/common/FailureResponse.java
  dateroad-api/src/main/java/org/dateroad/common/GlobalExceptionHandler.java
  dateroad-api/src/main/java/org/dateroad/common/SuccessResponse.java
Labels: refactor, setting, 정원

#16 [FEAT] UserId Argument Resolver 구현- #15
  dateroad-api/src/main/java/org/dateroad/auth/argumentresolve/UserId.java
  dateroad-api/src/main/java/org/dateroad/auth/argumentresolve/UserIdArgumentResolver.java
  dateroad-api/src/main/java/org/dateroad/auth/config/WebConfig.java
Labels: feat, 성준

#18 [FEAT] Jwt 세팅 설계 변경 - #17
  dateroad-api/src/main/java/org/dateroad/auth/jwt/JwtGenerator.java
  dateroad-api/src/main/java/org/dateroad/auth/jwt/JwtProvider.java
  dateroad-api/src/main/java/org/dateroad/auth/jwt/JwtValidator.java
  dateroad-api/src/main/java/org/dateroad/auth/jwt/KeyProvider.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
Labels: feat, 성준

#21 [FEAT] Place와 Image Entity 필드 sequence 필드추가
  dateroad-domain/src/main/java/org/dateroad/advertisement/domain/Advertisment.java
  dateroad-domain/src/main/java/org/dateroad/date/domain/Course.java
  dateroad-domain/src/main/java/org/dateroad/date/domain/Date.java
  dateroad-domain/src/main/java/org/dateroad/dateAccess/domain/DateAccess.java
  dateroad-domain/src/main/java/org/dateroad/image/domain/Image.java
  dateroad-domain/src/main/java/org/dateroad/like/domain/Like.java
  dateroad-domain/src/main/java/org/dateroad/place/domain/CoursePlace.java
  dateroad-domain/src/main/java/org/dateroad/place/domain/DatePlace.java
  dateroad-domain/src/main/java/org/dateroad/place/domain/Place.java
  dateroad-domain/src/main/java/org/dateroad/point/domain/Point.java
  dateroad-domain/src/main/java/org/dateroad/tag/domain/CourseTag.java
  dateroad-domain/src/main/java/org/dateroad/tag/domain/DateTag.java
  dateroad-domain/src/main/java/org/dateroad/tag/domain/UserTag.java
  dateroad-domain/src/main/java/org/dateroad/user/domain/User.java
Labels: feat, 기훈, beautiful

#23 [FEAT] S3 기본 세팅 - #13
  dateroad-external/build.gradle
  dateroad-external/src/main/java/org/dateroad/s3/AWSConfig.java
  dateroad-external/src/main/java/org/dateroad/s3/S3Service.java
Labels: feat, 정원

#24 [SETTING] OpenFeign (카카오, 애플) 세팅 - #19
  dateroad-api/build.gradle
  dateroad-api/src/main/java/org/dateroad/DateroadApplication.java
  dateroad-api/src/main/java/org/dateroad/auth/config/SecurityConfig.java
  dateroad-common/build.gradle
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
  dateroad-common/src/main/java/org/dateroad/common/ObjectMapperConfig.java
  dateroad-external/build.gradle
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleClientPublicKeyGenerator.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleFeignApi.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleIdentityJWTParser.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleIdentityJWTValidator.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/ApplePlatformUserIdProvider.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/ApplePublicKey.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/ApplePublicKeys.java
  dateroad-external/src/main/java/org/dateroad/feign/config/FeignConfig.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/KakaoAccessTokenRes.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/KakaoErrorRes.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/KakaoFeignApi.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/KakaoPlatformUserIdProvider.java
Labels: feat, setting, 성준

#25 [FEAT] 데이트 코스 전체 조회 API 구현
  dateroad-api/src/main/java/org/dateroad/course/api/CourseController.java
  dateroad-api/src/main/java/org/dateroad/course/dto/request/CourseGetAllReq.java
  dateroad-api/src/main/java/org/dateroad/course/dto/response/CourseGetAllRes.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseSpecifications.java
  dateroad-domain/src/main/java/org/dateroad/date/domain/Course.java
  dateroad-domain/src/main/java/org/dateroad/date/repository/CourseRepository.java
  dateroad-domain/src/main/java/org/dateroad/image/domain/Image.java
  dateroad-domain/src/main/java/org/dateroad/image/repository/ImageRepository.java
  dateroad-domain/src/main/java/org/dateroad/like/repository/LikeRepository.java
  dateroad-domain/src/main/java/org/dateroad/place/repository/CoursePlaceRepository.java
Labels: feat, 기훈, beautiful

#30 [FEAT] 광고 전체 조회 API 구현
  dateroad-api/src/main/java/org/dateroad/advertisment/api/AdvertismentController.java
  dateroad-api/src/main/java/org/dateroad/advertisment/dto/response/AdvGetAllRes.java
  dateroad-api/src/main/java/org/dateroad/advertisment/service/AdvertismentService.java
  dateroad-api/src/main/java/org/dateroad/course/api/CourseController.java
  dateroad-domain/src/main/java/org/dateroad/adImage/domain/AdImage.java
  dateroad-domain/src/main/java/org/dateroad/adImage/repository/AdImageRepository.java
  dateroad-domain/src/main/java/org/dateroad/advertisement/domain/AdTagType.java
  dateroad-domain/src/main/java/org/dateroad/advertisement/domain/Advertisment.java
  dateroad-domain/src/main/java/org/dateroad/advertisement/repository/AdvertismentRepository.java
Labels: feat, 기훈

#28 [FEAT] 열람 데이트 코스 전체 조회 API 구현 - #26
  dateroad-api/src/main/java/org/dateroad/course/api/CourseController.java
  dateroad-api/src/main/java/org/dateroad/course/dto/response/CourseDtoRes.java
  dateroad-api/src/main/java/org/dateroad/course/dto/response/CourseGetAllRes.java
  dateroad-api/src/main/java/org/dateroad/course/dto/response/DateAccessGetAllRes.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
  dateroad-domain/src/main/java/org/dateroad/dateAccess/repository/DataAccessRepository.java
  dateroad-domain/src/main/java/org/dateroad/image/repository/ImageRepository.java
  dateroad-domain/src/main/java/org/dateroad/like/repository/LikeRepository.java
  dateroad-domain/src/main/java/org/dateroad/place/domain/CoursePlace.java
  dateroad-domain/src/main/java/org/dateroad/place/domain/DatePlace.java
  dateroad-domain/src/main/java/org/dateroad/place/domain/Place.java
Labels: feat, 기훈

#46 [REFACTOR] 포인트 내역조회 API 수정 - #44
  dateroad-api/src/main/java/org/dateroad/point/api/PointController.java
  dateroad-api/src/main/java/org/dateroad/point/dto/response/PointDto.java
  dateroad-api/src/main/java/org/dateroad/point/dto/response/PointGetAllRes.java
  dateroad-api/src/main/java/org/dateroad/point/service/PointService.java
Labels: chore, refactor

#49 [FEAT] 전체 코드 오류 및 리팩터링 진행 - #47
  dateroad-api/src/main/java/org/dateroad/advertisment/dto/response/AdvGetAllRes.java
  dateroad-api/src/main/java/org/dateroad/course/dto/response/CourseDtoRes.java
  dateroad-api/src/main/java/org/dateroad/course/dto/response/CourseGetAllRes.java
  dateroad-api/src/main/java/org/dateroad/course/dto/response/DateAccessGetAllRes.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseSpecifications.java
  dateroad-domain/src/main/java/org/dateroad/date/domain/DateBase.java
  dateroad-domain/src/main/java/org/dateroad/image/domain/Image.java
Labels: refactor, 기훈, beautiful

#48 [FEAT] 로그아웃 API 구현 - #45
  dateroad-api/src/main/java/org/dateroad/user/api/UserController.java
  dateroad-api/src/main/java/org/dateroad/user/service/AuthService.java
  dateroad-domain/src/main/java/org/dateroad/refreshtoken/repository/RefreshTokenRepository.java
Labels: feat, 성준

#52 [FEAT] 데이트 일정 삭제 API 구현 - #36
  dateroad-api/src/main/java/org/dateroad/auth/config/SecurityConfig.java
  dateroad-api/src/main/java/org/dateroad/date/api/DateController.java
  dateroad-api/src/main/java/org/dateroad/date/service/DateService.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
  dateroad-common/src/main/java/org/dateroad/exception/ForbiddenException.java
  dateroad-domain/src/main/java/org/dateroad/date/domain/Course.java
  dateroad-domain/src/main/java/org/dateroad/date/domain/DateBase.java
  dateroad-domain/src/main/java/org/dateroad/date/repository/DatePlaceRepository.java
  dateroad-domain/src/main/java/org/dateroad/date/repository/DateTagRepository.java
Labels: feat, 정원

#53 [FEAT] 회원탈퇴 API 구현 - #50
  .gitignore
  dateroad-api/src/main/java/org/dateroad/user/api/UserController.java
  dateroad-api/src/main/java/org/dateroad/user/dto/request/AppleWithdrawAuthCodeReq.java
  dateroad-api/src/main/java/org/dateroad/user/service/AuthService.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
  dateroad-common/src/main/java/org/dateroad/exception/BadRequestException.java
  dateroad-domain/src/main/java/org/dateroad/user/domain/User.java
  dateroad-external/build.gradle
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleClientPublicKeyGenerator.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleClientSecretGenerator.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleFeignApi.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleFeignProvider.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleIdentityJWTValidator.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleProperties.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleTokenRes.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/KakaoErrorRes.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/KakaoFeignApi.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/KakaoFeignProvider.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/KakaoHeaderType.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/KakaoPlatformUserIdProvider.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/KakaoProperties.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/KakaoRequestType.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/dto/response/KaKaoErrorRes.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/dto/response/KaKaoUnlinkRes.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/dto/response/KakaoAccessTokenInfoRes.java
Labels: feat, 성준

#64 [FIX] 삭제 파일 rebase - #63
  .github/workflows/CICD-dev.yml
  .gitignore
  dateroad-api/src/main/java/org/dateroad/advertisment/dto/response/AdvGetAllRes.java
  dateroad-api/src/main/java/org/dateroad/auth/config/SecurityConfig.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseSpecifications.java
  dateroad-api/src/main/java/org/dateroad/date/api/DateController.java
  dateroad-api/src/main/java/org/dateroad/date/dto/request/DateCreateReq.java
  dateroad-api/src/main/java/org/dateroad/date/dto/request/PlaceCreateReq.java
  dateroad-api/src/main/java/org/dateroad/date/dto/request/TagCreateReq.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/DateDetailRes.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/PlaceGetRes.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/TagGetRes.java
  dateroad-api/src/main/java/org/dateroad/date/service/DateRepository.java
  dateroad-api/src/main/java/org/dateroad/date/service/DateService.java
  dateroad-api/src/main/java/org/dateroad/user/api/UserController.java
  dateroad-api/src/main/java/org/dateroad/user/dto/request/AppleWithdrawAuthCodeReq.java
  dateroad-api/src/main/java/org/dateroad/user/service/AuthService.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
  dateroad-common/src/main/java/org/dateroad/common/ObjectMapperConfig.java
  dateroad-common/src/main/java/org/dateroad/exception/BadRequestException.java
  dateroad-common/src/main/java/org/dateroad/exception/ForbiddenException.java
  dateroad-domain/src/main/java/org/dateroad/date/repository/DatePlaceRepository.java
  dateroad-domain/src/main/java/org/dateroad/date/repository/DateTagRepository.java
  dateroad-domain/src/main/java/org/dateroad/dateAccess/repository/DateAccessRepository.java
  dateroad-domain/src/main/java/org/dateroad/place/domain/DatePlace.java
  dateroad-domain/src/main/java/org/dateroad/place/repository/CoursePlaceRepository.java
  dateroad-domain/src/main/java/org/dateroad/refreshtoken/repository/RefreshTokenRepository.java
  dateroad-domain/src/main/java/org/dateroad/tag/domain/DateTag.java
  dateroad-domain/src/main/java/org/dateroad/user/domain/User.java
  dateroad-domain/src/main/java/org/dateroad/user/repository/UserRepository.java
  dateroad-external/build.gradle
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleClientPublicKeyGenerator.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleClientSecretGenerator.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleFeignApi.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleFeignProvider.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleIdentityJWTValidator.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleProperties.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleTokenRes.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/KakaoErrorRes.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/KakaoFeignApi.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/KakaoFeignProvider.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/KakaoHeaderType.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/KakaoPlatformUserIdProvider.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/KakaoProperties.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/KakaoRequestType.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/dto/response/KaKaoErrorRes.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/dto/response/KaKaoUnlinkRes.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/dto/response/KakaoAccessTokenInfoRes.java
Labels: fix, 기훈

#67 [FEAT] 지난 & 다가올 데이트 일정 전체 조회 API 구현 - #38
  dateroad-api/src/main/java/org/dateroad/date/api/DateController.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/DateDetailRes.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/DateGetRes.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/DatesGetRes.java
  dateroad-api/src/main/java/org/dateroad/date/service/DateRepository.java
  dateroad-api/src/main/java/org/dateroad/date/service/DateService.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
Labels: feat, 정원, beautiful

#60 [FEAT] 유저 프로필 조회 API(메인) - #57
  dateroad-api/src/main/java/org/dateroad/user/api/UserController.java
  dateroad-api/src/main/java/org/dateroad/user/dto/response/UserInfoMainRes.java
  dateroad-api/src/main/java/org/dateroad/user/service/UserService.java
Labels: feat, 성준

#59 [FEAT] 메인 다가올 일정(1개) 조회 API - #58
  dateroad-api/src/main/java/org/dateroad/date/api/DateController.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/DateGetNearestRes.java
  dateroad-api/src/main/java/org/dateroad/date/service/DateRepository.java
  dateroad-api/src/main/java/org/dateroad/date/service/DateService.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
Labels: feat, 성준

#74 [FEAT] 데이트 코스 좋아요 등록 API 구현 - #68
  dateroad-api/src/main/java/org/dateroad/course/api/CourseController.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-api/src/main/java/org/dateroad/date/service/DateService.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
  dateroad-domain/src/main/java/org/dateroad/like/repository/LikeRepository.java
Labels: feat, 정원

#75 [SETTING] Redis Docker 추가 Docker Compose 구현 #72
  docker-compose.yml
Labels: feat, setting, 기훈, beautiful

#73 [FEAT] 데이트 코스 상세 조회 API - #66
  dateroad-api/src/main/java/org/dateroad/Image/service/ImageService.java
  dateroad-api/src/main/java/org/dateroad/auth/filter/JwtAuthenticationFilter.java
  dateroad-api/src/main/java/org/dateroad/course/api/CourseController.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/CourseGetDetailRes.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
  dateroad-domain/src/main/java/org/dateroad/date/repository/CourseRepository.java
  dateroad-domain/src/main/java/org/dateroad/dateAccess/repository/DateAccessRepository.java
  dateroad-domain/src/main/java/org/dateroad/image/domain/Image.java
  dateroad-domain/src/main/java/org/dateroad/image/repository/ImageRepository.java
  dateroad-domain/src/main/java/org/dateroad/like/repository/LikeRepository.java
  dateroad-domain/src/main/java/org/dateroad/place/repository/CoursePlaceRepository.java
  dateroad-domain/src/main/java/org/dateroad/tag/domain/CourseTag.java
  dateroad-domain/src/main/java/org/dateroad/tag/repository/CourseTagRepository.java
  dateroad-external/build.gradle
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleClientSecretGenerator.java
Labels: feat, 성준

#77 [FEAT] 데이트 코스 좋아요 삭제 API 구현 - #68
  dateroad-api/src/main/java/org/dateroad/auth/filter/JwtAuthenticationFilter.java
  dateroad-api/src/main/java/org/dateroad/course/api/CourseController.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
Labels: feat, 정원

#70 [FEAT] 포인트 사용 [유저 데이트 코스 열람] API - #65
  dateroad-api/build.gradle
  dateroad-api/src/main/java/org/dateroad/config/RedisStreamConfig.java
  dateroad-api/src/main/java/org/dateroad/course/api/CourseController.java
  dateroad-api/src/main/java/org/dateroad/course/dto/request/PointUseReq.java
  dateroad-api/src/main/java/org/dateroad/course/facade/AsyncService.java
  dateroad-api/src/main/java/org/dateroad/course/service/CoursePaymentType.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-api/src/main/java/org/dateroad/point/event/FreeEventListener.java
  dateroad-api/src/main/java/org/dateroad/point/event/pointEventListener.java
  dateroad-api/src/main/java/org/dateroad/point/service/PointService.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
  dateroad-domain/src/main/java/org/dateroad/dateAccess/domain/DateAccess.java
  dateroad-domain/src/main/java/org/dateroad/user/domain/User.java
Labels: feat, 기훈

#81 [FEAT] 광고 상세 조회 API - #71
  dateroad-api/src/main/java/org/dateroad/advertisment/api/AdvertismentController.java
  dateroad-api/src/main/java/org/dateroad/advertisment/dto/response/AdvGetDetailRes.java
  dateroad-api/src/main/java/org/dateroad/advertisment/service/AdvertismentService.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
  dateroad-domain/src/main/java/org/dateroad/adImage/repository/AdImageRepository.java
Labels: feat, 기훈, beautiful

#76 [FEAT] 유저 프로필 조회 API(마이페이지) - #61
  dateroad-api/src/main/java/org/dateroad/user/api/UserController.java
  dateroad-api/src/main/java/org/dateroad/user/dto/response/UserInfoGetMyPageRes.java
  dateroad-api/src/main/java/org/dateroad/user/service/UserService.java
  dateroad-domain/src/main/java/org/dateroad/tag/domain/UserTag.java
  dateroad-domain/src/main/java/org/dateroad/tag/repository/UserTagRepository.java
Labels: feat, 성준

#83 [FEAT] 데이트 코스 필터링 조회(메인) API 구현 - #79
  dateroad-api/src/main/java/org/dateroad/course/api/CourseController.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
  dateroad-domain/src/main/java/org/dateroad/date/repository/CourseRepository.java
Labels: feat, 정원, 정원이좋아행

#84 [FEAT] 유저 등록 데이트 코스 조회 API(내가 등록한 코스) 구현 - #80
  dateroad-api/src/main/java/org/dateroad/course/api/CourseController.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-domain/src/main/java/org/dateroad/date/repository/CourseRepository.java
Labels: feat, 정원

#86 [FIX] 데이트 일정 상세 조회 API 응답 스펙 변경 - #85
  dateroad-api/src/main/java/org/dateroad/date/dto/response/DateDetailRes.java
  dateroad-api/src/main/java/org/dateroad/date/service/DateService.java
Labels: fix, 정원

#87 [FEAT] 회원가입 API 에서 프로필 사진 S3 적용 - #78
  dateroad-api/src/main/java/org/dateroad/user/api/UserController.java
  dateroad-api/src/main/java/org/dateroad/user/dto/request/UserSignUpReq.java
  dateroad-api/src/main/java/org/dateroad/user/service/AuthService.java
Labels: feat, 성준

#89 Feature/#82
  dateroad-api/src/main/java/org/dateroad/course/api/CourseController.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
  dateroad-domain/src/main/java/org/dateroad/date/repository/CourseRepository.java
  dateroad-domain/src/main/java/org/dateroad/dateAccess/repository/DateAccessRepository.java
  dateroad-domain/src/main/java/org/dateroad/image/repository/ImageRepository.java
  dateroad-domain/src/main/java/org/dateroad/like/repository/LikeRepository.java
  dateroad-domain/src/main/java/org/dateroad/place/repository/CoursePlaceRepository.java
  dateroad-domain/src/main/java/org/dateroad/tag/repository/CourseTagRepository.java
Labels: feat, 기훈, beautiful

#91 코스 등록시 Point 추가 로직 구현 - #90
  dateroad-api/src/main/java/org/dateroad/course/api/CourseController.java
  dateroad-api/src/main/java/org/dateroad/course/dto/request/PointUseReq.java
  dateroad-api/src/main/java/org/dateroad/course/facade/AsyncService.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-api/src/main/java/org/dateroad/point/event/pointEventListener.java
Labels: fix, feat, 기훈, beautiful

#93 [REFACTOR] Gradle 의존성 분리 및 제거 - #92
  build.gradle
  dateroad-api/build.gradle
  dateroad-common/build.gradle
  dateroad-domain/build.gradle
  dateroad-external/build.gradle
Labels: 기훈, beautiful

#96 [FEAT] 유저 프로필 수정 API - #88
  dateroad-api/src/main/java/org/dateroad/user/api/UserController.java
  dateroad-api/src/main/java/org/dateroad/user/service/AuthService.java
  dateroad-api/src/main/java/org/dateroad/user/service/UserService.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
  dateroad-domain/src/main/java/org/dateroad/tag/repository/UserTagRepository.java
  dateroad-domain/src/main/java/org/dateroad/user/domain/User.java
  dateroad-external/src/main/java/org/dateroad/s3/S3Service.java
Labels: feat, 성준

#99 [FEAT] AdTagType 제거 - #98
  dateroad-api/src/main/java/org/dateroad/advertisment/dto/response/AdvGetAllRes.java
  dateroad-domain/src/main/java/org/dateroad/advertisement/domain/AdTagType.java
  dateroad-domain/src/main/java/org/dateroad/advertisement/domain/Advertisment.java
Labels: del, 기훈, beautiful

#104 [REFACTOR] 전반적 코드 정리
  dateroad-api/src/main/java/org/dateroad/DateroadApplication.java
  dateroad-api/src/main/java/org/dateroad/advertisement/api/AdvertisementApi.java
  dateroad-api/src/main/java/org/dateroad/advertisement/api/AdvertisementController.java
  dateroad-api/src/main/java/org/dateroad/advertisement/dto/response/AdvGetAllRes.java
  dateroad-api/src/main/java/org/dateroad/advertisement/dto/response/AdvGetDetailRes.java
  dateroad-api/src/main/java/org/dateroad/advertisement/service/AdvertisementService.java
  dateroad-api/src/main/java/org/dateroad/advertisment/api/AdvertismentController.java
  dateroad-api/src/main/java/org/dateroad/advertisment/dto/response/AdvGetAllRes.java
  dateroad-api/src/main/java/org/dateroad/advertisment/service/AdvertismentService.java
  dateroad-api/src/main/java/org/dateroad/auth/jwt/JwtProvider.java
  dateroad-api/src/main/java/org/dateroad/auth/jwt/JwtValidator.java
  dateroad-api/src/main/java/org/dateroad/auth/jwt/refreshtoken/RefreshTokenGenerator.java
  dateroad-api/src/main/java/org/dateroad/config/AsyncConfig.java
  dateroad-api/src/main/java/org/dateroad/config/RedisStreamConfig.java
  dateroad-api/src/main/java/org/dateroad/course/api/CourseController.java
  dateroad-api/src/main/java/org/dateroad/course/dto/request/CoursePlaceGetReq.java
  dateroad-api/src/main/java/org/dateroad/course/dto/request/PointUseReq.java
  dateroad-api/src/main/java/org/dateroad/course/dto/request/TagCreateReq.java
  dateroad-api/src/main/java/org/dateroad/course/dto/response/CourseCreateRes.java
  dateroad-api/src/main/java/org/dateroad/course/dto/response/CourseDtoGetRes.java
  dateroad-api/src/main/java/org/dateroad/course/service/AsyncService.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseTagService.java
  dateroad-api/src/main/java/org/dateroad/date/api/DateController.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/CourseGetDetailRes.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/DateGetNearestRes.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/DateGetRes.java
  dateroad-api/src/main/java/org/dateroad/date/service/DateRepository.java
  dateroad-api/src/main/java/org/dateroad/date/service/DateService.java
  dateroad-api/src/main/java/org/dateroad/image/service/ImageService.java
  dateroad-api/src/main/java/org/dateroad/point/api/PointController.java
  dateroad-api/src/main/java/org/dateroad/point/event/FreeEventListener.java
  dateroad-api/src/main/java/org/dateroad/point/event/PointEventListener.java
  dateroad-api/src/main/java/org/dateroad/point/service/PointService.java
  dateroad-api/src/main/java/org/dateroad/user/api/UserController.java
  dateroad-api/src/main/java/org/dateroad/user/dto/request/UserSignUpReq.java
  dateroad-api/src/main/java/org/dateroad/user/dto/response/UserInfoGetMyPageRes.java
  dateroad-api/src/main/java/org/dateroad/user/service/AuthService.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
  dateroad-domain/src/main/java/org/dateroad/adImage/domain/AdImage.java
  dateroad-domain/src/main/java/org/dateroad/adImage/repository/AdImageRepository.java
  dateroad-domain/src/main/java/org/dateroad/advertisement/domain/AdTagType.java
  dateroad-domain/src/main/java/org/dateroad/advertisement/domain/Advertisement.java
  dateroad-domain/src/main/java/org/dateroad/advertisement/repository/AdvertisementRepository.java
  dateroad-domain/src/main/java/org/dateroad/date/domain/Course.java
  dateroad-domain/src/main/java/org/dateroad/dateAccess/domain/DateAccess.java
  dateroad-domain/src/main/java/org/dateroad/place/repository/CoursePlaceRepository.java
  dateroad-domain/src/main/java/org/dateroad/point/repository/PointRepository.java
  dateroad-domain/src/main/java/org/dateroad/refreshtoken/domain/RefreshToken.java
  dateroad-domain/src/main/java/org/dateroad/tag/repository/UserTagRepository.java
  dateroad-domain/src/main/java/org/dateroad/user/domain/Platform.java
  dateroad-domain/src/main/java/org/dateroad/user/domain/User.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleFeignApi.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleIdentityJWTValidator.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/ApplePublicKeys.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/KakaoHeaderType.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/dto/response/KakaoErrorRes.java
  dateroad-external/src/main/java/org/dateroad/s3/S3Service.java
Labels: refactor, 정원

#106 [REFACROT] 코드 리팩토링 - #102
  dateroad-api/src/main/java/org/dateroad/advertisement/dto/response/AdvGetDetailRes.java
  dateroad-api/src/main/java/org/dateroad/advertisement/service/AdvertisementService.java
  dateroad-api/src/main/java/org/dateroad/auth/jwt/JwtValidator.java
  dateroad-api/src/main/java/org/dateroad/auth/jwt/TokenType.java
  dateroad-api/src/main/java/org/dateroad/auth/jwt/refreshtoken/RefreshTokenGenerator.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-api/src/main/java/org/dateroad/user/api/UserController.java
  dateroad-api/src/main/java/org/dateroad/user/service/AuthService.java
  dateroad-domain/src/main/java/org/dateroad/advertisement/repository/AdvertisementRepository.java
  dateroad-domain/src/main/java/org/dateroad/refreshtoken/repository/RefreshTokenRepository.java
  dateroad-external/src/main/java/org/dateroad/feign/apple/AppleFeignProvider.java
  dateroad-external/src/main/java/org/dateroad/feign/kakao/KakaoPlatformUserIdProvider.java
Labels: refactor, 성준

#111 [DOCS] Swagger Authorization 추가 - #110
  dateroad-api/src/main/java/org/dateroad/date/api/DateApi.java
Labels: docs, 기훈, beautiful

#113 [FIX] Course description 필드 길이 변경 - #112
  dateroad-domain/src/main/java/org/dateroad/date/domain/Course.java
Labels: fix, 정원

#120 [FEAT] 데이트 코스 상세 조회 dto 스펙 변경 - #118
  dateroad-api/src/main/java/org/dateroad/date/api/DateApi.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/PlaceGetRes.java
Labels: feat, 정원

#122 [REFACTOR] 엔티티 변경에 따른 Course조회 로직 수정 - #116
  dateroad-api/src/main/java/org/dateroad/course/service/AsyncService.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
Labels: refactor, 기훈, beautiful

#124 [FEAT] cost 11일때 10만원 이상 조회 로직 추가 - #123
  dateroad-api/src/main/java/org/dateroad/course/service/CourseSpecifications.java
Labels: feat, 기훈, beautiful

#126 [DOCS] user API swagger 명세 작성 - #125
  dateroad-api/src/main/java/org/dateroad/user/api/UserApi.java
  dateroad-api/src/main/java/org/dateroad/user/api/UserController.java
Labels: docs, feat, 기훈, beautiful

#133 [feat] 확장자에 따라 저장로직 변경 - #132
  dateroad-external/src/main/java/org/dateroad/s3/S3Service.java
Labels: feat, 기훈, beautiful, 정원이좋아행

#137 [FIX] 만단위 -> 원단위로 변경 - #136
  dateroad-api/src/main/java/org/dateroad/course/service/CourseSpecifications.java
Labels: fix, 기훈

#139 [FIX] time 포맷 및 데이터 일정 생성 place.name -> title 변경 - #138
  dateroad-api/src/main/java/org/dateroad/course/api/CourseApi.java
  dateroad-api/src/main/java/org/dateroad/course/dto/request/CourseCreateReq.java
  dateroad-api/src/main/java/org/dateroad/date/api/DateApi.java
  dateroad-api/src/main/java/org/dateroad/date/dto/request/DateCreateReq.java
  dateroad-api/src/main/java/org/dateroad/date/dto/request/PlaceCreateReq.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/DateDetailRes.java
  dateroad-api/src/main/java/org/dateroad/date/service/DateService.java
Labels: fix, 기훈, beautiful

#131 [feat] Validator 구현 - #130
  dateroad-api/src/main/java/org/dateroad/auth/jwt/JwtProvider.java
  dateroad-api/src/main/java/org/dateroad/common/ValidatorUtil.java
  dateroad-api/src/main/java/org/dateroad/user/service/AuthService.java
  dateroad-api/src/main/java/org/dateroad/user/service/UserService.java
Labels: feat, 성준

#141 [FIX] DateDetail dto 수정 - #112
  dateroad-api/src/main/java/org/dateroad/date/dto/response/DateDetailRes.java
Labels: fix, 정원, beautiful

#143 [FIX] securityConfig whiteList API 스웨거 인증 제거 #142
  dateroad-api/src/main/java/org/dateroad/advertisement/api/AdvertisementController.java
  dateroad-api/src/main/java/org/dateroad/point/api/PointController.java
  dateroad-api/src/main/java/org/dateroad/user/api/UserApi.java
Labels: fix, 성준

#145 [FIX] 코스 상세조회 이슈 대응 - #144
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-domain/src/main/java/org/dateroad/date/repository/CourseRepository.java
Labels: fix, 성준

#149 [REFACTOR] 코드 정리 - #146
  dateroad-api/src/main/java/org/dateroad/user/api/UserController.java
  dateroad-api/src/main/java/org/dateroad/user/service/AuthService.java
Labels: refactor, 성준

#148 [FIX] dateTimeFormat 제거 - #147
  dateroad-api/src/main/java/org/dateroad/course/dto/request/CourseCreateReq.java
  dateroad-api/src/main/java/org/dateroad/date/dto/request/DateCreateReq.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/DateDetailRes.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/DateGetNearestRes.java
Labels: fix, 기훈

#153 [FIX] Date 필터링 조회 리스트 순서 변경 - #152
  dateroad-api/src/main/java/org/dateroad/date/service/DateRepository.java
Labels: fix, 정원

#160 [FIX] 유저 프로필 이미지 null 허용 - #155
  dateroad-api/src/main/java/org/dateroad/user/api/UserController.java
  dateroad-api/src/main/java/org/dateroad/user/service/AuthService.java
  dateroad-api/src/main/java/org/dateroad/user/service/UserService.java
Labels: fix, 성준

#159 [FIX] 코스 좋아요 생성에 내 글 좋아요 Validate 추가 - #156
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
Labels: fix, 정원

#164 [FIX] Advertisement description 길이 추가 - #163
  dateroad-domain/src/main/java/org/dateroad/advertisement/domain/Advertisement.java
Labels: fix, 정원

#168 [FEAT] isCourseMine, isAccess 매칭 - #167
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
Labels: feat, 성준

#170 [FIX] DateAccess 연관관계 매핑 수정 - #169
  dateroad-domain/src/main/java/org/dateroad/dateAccess/domain/DateAccess.java
Labels: fix, 정원

#172 [CHORE] 광고상세조회 api response dto 필드명 변경 - #171
  dateroad-api/src/main/java/org/dateroad/advertisement/dto/response/AdvGetDetailRes.java
Labels: chore, 성준

#175 [FEAT] 최신순 로직 변경 - #174
  dateroad-api/src/main/java/org/dateroad/point/service/PointService.java
  dateroad-domain/src/main/java/org/dateroad/point/repository/PointRepository.java
Labels: feat, 기훈, beautiful

#178 [FEAT] 유저 탈퇴 시, 관련 데이터 삭제 - #176
  dateroad-api/src/main/java/org/dateroad/date/service/DateRepository.java
  dateroad-api/src/main/java/org/dateroad/user/service/AuthService.java
  dateroad-api/src/main/java/org/dateroad/user/service/UserService.java
  dateroad-domain/src/main/java/org/dateroad/date/repository/CourseRepository.java
  dateroad-domain/src/main/java/org/dateroad/dateAccess/repository/DateAccessRepository.java
  dateroad-domain/src/main/java/org/dateroad/like/repository/LikeRepository.java
  dateroad-domain/src/main/java/org/dateroad/point/repository/PointRepository.java
  dateroad-domain/src/main/java/org/dateroad/tag/repository/UserTagRepository.java
  dateroad-domain/src/main/java/org/dateroad/user/domain/User.java
  dateroad-domain/src/main/java/org/dateroad/user/repository/UserRepository.java
Labels: feat, 성준

#181 [FIX] 유저 탈퇴 로직 수정 - #179
  dateroad-api/src/main/java/org/dateroad/date/service/DateRepository.java
  dateroad-api/src/main/java/org/dateroad/user/service/AuthService.java
  dateroad-domain/src/main/java/org/dateroad/date/domain/DateBase.java
  dateroad-domain/src/main/java/org/dateroad/date/repository/CourseRepository.java
Labels: fix, 성준

#183 [FIX] 유저 탈퇴 플랫폼아이디 수정 - #182
  dateroad-api/src/main/java/org/dateroad/user/service/AuthService.java
  dateroad-domain/src/main/java/org/dateroad/user/domain/User.java
Labels: fix, 성준

#180 [FEAT] 장소 및 데이트 검증로직 추가 - #177
  dateroad-api/src/main/java/org/dateroad/common/ValidatorUtil.java
  dateroad-api/src/main/java/org/dateroad/course/api/CourseController.java
  dateroad-api/src/main/java/org/dateroad/course/dto/request/CourseCreateReq.java
  dateroad-api/src/main/java/org/dateroad/date/dto/request/DateCreateReq.java
  dateroad-api/src/main/java/org/dateroad/user/service/AuthService.java
  dateroad-api/src/main/java/org/dateroad/user/service/UserService.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
Labels: feat, 기훈, beautiful

#190 [FIX] 가장 가까운 일정 조회 쿼리 수정 - #189
  dateroad-api/src/main/java/org/dateroad/date/service/DateRepository.java
  dateroad-api/src/main/java/org/dateroad/date/service/DateService.java
Labels: fix, 성준

#193 [FIX] 코스 전체조회 로직 및 내가 생성한 코스 데이트 등록 수정 - #192
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseSpecifications.java
Labels: fix, 기훈, beautiful

#197 [TEST] jacoco 설정 및 CreateDate Service 테스트
  dateroad-api/build.gradle
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-api/src/main/java/org/dateroad/date/dto/request/DateCreateReq.java
  dateroad-api/src/test/java/org/dateroad/date/service/DateServiceTest.java
Labels: chore, test, 정원

#199 [FIX] getDate 조회 순서에 startAt 추가 - #198
  dateroad-api/src/main/java/org/dateroad/date/service/DateRepository.java
Labels: fix, 정원

#201 [FIX] 필터 적용후 최신등록순 조회 - #200
  dateroad-api/src/main/java/org/dateroad/course/service/CourseSpecifications.java
Labels: fix, 기훈

#203 [fix] 좋아요 수 메서드 변경 - #202
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-domain/src/main/java/org/dateroad/like/repository/LikeRepository.java
Labels: fix, 성준

#205 [DOCS] swagger 명세 예시 수정 - #204
  dateroad-api/src/main/java/org/dateroad/course/api/CourseApi.java
  dateroad-api/src/main/java/org/dateroad/date/api/DateApi.java
  dateroad-api/src/main/java/org/dateroad/user/api/UserApi.java
Labels: docs, 기훈, beautiful

#207 [FIX] 광고 이미지 Repository 로직 수정 - #206
  dateroad-api/src/main/java/org/dateroad/advertisement/service/AdvertisementService.java
  dateroad-domain/src/main/java/org/dateroad/adImage/repository/AdImageRepository.java
Labels: fix, 정원

#194 [FEAT] 에러 Response 디테일 구현 로직 추가 - #188 [머지 앱잼끝나고 할게요]
  dateroad-api/src/main/java/org/dateroad/common/FailureResponse.java
  dateroad-api/src/main/java/org/dateroad/common/GlobalExceptionHandler.java
  dateroad-api/src/main/java/org/dateroad/course/api/CourseApi.java
  dateroad-api/src/main/java/org/dateroad/course/api/CourseController.java
  dateroad-api/src/main/java/org/dateroad/course/dto/request/CourseCreateReq.java
  dateroad-api/src/main/java/org/dateroad/course/dto/request/CourseGetAllReq.java
  dateroad-api/src/main/java/org/dateroad/course/dto/request/PointUseReq.java
  dateroad-api/src/main/java/org/dateroad/date/api/DateApi.java
  dateroad-api/src/main/java/org/dateroad/date/api/DateController.java
  dateroad-api/src/main/java/org/dateroad/date/dto/request/DateCreateReq.java
  dateroad-common/build.gradle
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
  dateroad-common/src/main/java/org/dateroad/exception/DateRoadException.java
Labels: fix, refactor, 기훈

#209 [FIX] 이미지 비동기 upload - #208
  dateroad-api/src/main/java/org/dateroad/image/service/ImageService.java
  dateroad-external/src/main/java/org/dateroad/s3/S3Service.java
Labels: fix, feat, refactor, 기훈

#211 [FEAT] S3 이미지 리스트 반환 로직 구현 - #210
  dateroad-api/src/main/java/org/dateroad/image/service/ImageService.java
  dateroad-external/src/main/java/org/dateroad/s3/S3Service.java
Labels: feat, 기훈, beautiful
