Repository TeamDATEROAD/DATEROAD-SERVER, pull requests merged in 2024-09, with the labels that each got.

#238 [FIX] Redis Cluster Transactional 해제 및 Event description 변경 - #237
  dateroad-api/src/main/java/org/dateroad/config/RedisConfig.java
  dateroad-api/src/main/java/org/dateroad/course/api/CourseController.java
  dateroad-api/src/main/java/org/dateroad/course/dto/request/PointUseReq.java
Labels: fix, 기훈

#240 [FEAT] 프로필 수정 API 필드 추가 - #239
  dateroad-api/src/main/java/org/dateroad/user/api/UserApi.java
  dateroad-api/src/main/java/org/dateroad/user/api/UserController.java
  dateroad-api/src/main/java/org/dateroad/user/service/UserService.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
Labels: feat, 성준

#244 [FIX] 프로필 수정 API 유저 중복검증 로직 추가 - #243
  dateroad-api/src/main/java/org/dateroad/user/service/AuthService.java
  dateroad-api/src/main/java/org/dateroad/user/service/UserService.java
Labels: fix, 성준

#246 [ FIX] 멀티파트 Null 이슈 해결- #245
  dateroad-api/src/main/java/org/dateroad/user/service/UserService.java
Labels: fix, 성준

#248 [FIX] 클러스터 쉘 파일 수정 - #247
  dateroad-api/src/main/java/org/dateroad/config/RedisConfig.java
  docker-compose-local.yml
  redis-cluster-remove.sh
  redis-cluster.sh
  redis_conf/redis-master-1.conf
  redis_conf/redis-master-2.conf
  redis_conf/redis-master-3.conf
  redis_conf/redis-slave-1.conf
  redis_conf/redis-slave-2.conf
  redis_conf/redis-slave-3.conf
Labels: fix, 성준, 기훈

#252 [FIX] 탈퇴하기 버그 픽스 - #251
  dateroad-api/src/main/java/org/dateroad/user/service/AuthService.java
Labels: fix, 성준

#254 [FIX] Redis Time out 제거 - #253
  dateroad-api/src/main/java/org/dateroad/config/RedisConfig.java
Labels: fix, 기훈

#256 [FIX] DockerFile 롤백 - #255
  Dockerfile
Labels: chore, 기훈

#259 [FIX] 프로필 수정 API 버그 픽스 - #258
  dateroad-api/src/main/java/org/dateroad/user/service/UserService.java
Labels: fix, 성준

#261 [FIX] 이미지 변경 버그 픽스 -#260
  dateroad-api/src/main/java/org/dateroad/user/service/UserService.java
Labels: fix, 성준

#278 [FIX] Course 삭제 오류 해결 - #277
  .gitignore
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
  dateroad-domain/src/main/java/org/dateroad/user/domain/User.java
Labels: fix, 정원

#280 [FEAT] Amplitude를 위한 일부 API 응답 변경 - #279
  dateroad-api/src/main/java/org/dateroad/common/Constants.java
  dateroad-api/src/main/java/org/dateroad/course/api/CourseApi.java
  dateroad-api/src/main/java/org/dateroad/course/api/CourseController.java
  dateroad-api/src/main/java/org/dateroad/course/dto/request/PointUseReq.java
  dateroad-api/src/main/java/org/dateroad/course/dto/response/CourseAccessGetAllRes.java
  dateroad-api/src/main/java/org/dateroad/course/dto/response/CourseCreateRes.java
  dateroad-api/src/main/java/org/dateroad/course/dto/response/DateAccessCreateRes.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-api/src/main/java/org/dateroad/date/api/DateApi.java
  dateroad-api/src/main/java/org/dateroad/date/api/DateController.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/DateCreateRes.java
  dateroad-api/src/main/java/org/dateroad/date/service/DateRepository.java
  dateroad-api/src/main/java/org/dateroad/date/service/DateService.java
  dateroad-api/src/test/java/org/dateroad/course/service/CourseServiceTest.java
  dateroad-domain/src/main/java/org/dateroad/date/repository/CourseRepository.java
  dateroad-domain/src/main/java/org/dateroad/dateAccess/repository/DateAccessRepository.java
Labels: feat, 정원

#284 [CHORE] 운영 서버 ci/cd workflow 설정 - #281
  .github/workflows/CI-main.yml
  .github/workflows/CICD-main.yml
Labels: chore, 정원

#289 [FIX] 유저 프로필 이미지 기본 url 오류 해결
  dateroad-external/src/main/java/org/dateroad/s3/S3Service.java
Labels: fix, 정원

#290 [FIX] Course 상세 조회 CoursePlace 순서 오류 해결 - #288
  .github/workflows/CICD-main.yml
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-domain/src/main/java/org/dateroad/place/repository/CoursePlaceRepository.java
Labels: fix, 정원

#292 [release] v1.0.1 릴리즈 - #291
  .github/workflows/CICD-main.yml
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-domain/src/main/java/org/dateroad/place/repository/CoursePlaceRepository.java
Labels: release, 정원
