Repository TeamDATEROAD/DATEROAD-SERVER, pull requests merged in 2024-08, with the labels that each got.

#217 [FIX] 사진저장로직 수정 - #216
  dateroad-api/src/main/java/org/dateroad/image/service/ImageService.java
Labels: fix, 기훈, beautiful

#219 [REFACTOR] 지역 Request 한글 및 Enum 변경 - #218
  dateroad-api/src/main/java/org/dateroad/auth/config/WebConfig.java
  dateroad-api/src/main/java/org/dateroad/common/FailureResponse.java
  dateroad-api/src/main/java/org/dateroad/common/GlobalExceptionHandler.java
  dateroad-api/src/main/java/org/dateroad/config/WebConfig.java
  dateroad-api/src/main/java/org/dateroad/course/api/CourseApi.java
  dateroad-api/src/main/java/org/dateroad/course/dto/response/CourseDtoGetRes.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/CourseGetDetailRes.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/DateDetailRes.java
  dateroad-api/src/test/java/org/dateroad/date/service/DateServiceTest.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
  dateroad-domain/src/main/java/org/dateroad/date/domain/Region.java
Labels: fix, refactor, 기훈

#221 [FIX] 프로필수정 멀티파트파일 nullable 수정 - #161
  dateroad-api/src/main/java/org/dateroad/user/api/UserApi.java
  dateroad-api/src/main/java/org/dateroad/user/api/UserController.java
  dateroad-api/src/test/java/org/dateroad/user/service/AuthServiceTest.java
Labels: fix, 성준

#224 [FEAT] 회원가입 디스코드 알림 웹훅 구현 - #223
  dateroad-api/src/main/java/org/dateroad/user/service/AuthService.java
  dateroad-api/src/test/java/org/dateroad/user/service/AuthServiceTest.java
  dateroad-common/src/main/java/org/dateroad/code/EventCode.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
  dateroad-common/src/main/java/org/dateroad/event/SignUpEventInfo.java
  dateroad-domain/src/main/java/org/dateroad/user/domain/User.java
  dateroad-domain/src/main/java/org/dateroad/user/repository/UserRepository.java
  dateroad-external/src/main/java/org/dateroad/config/FeignConfig.java
  dateroad-external/src/main/java/org/dateroad/feign/discord/DiscordFeignApi.java
  dateroad-external/src/main/java/org/dateroad/feign/discord/DiscordFeignProvider.java
  dateroad-external/src/main/java/org/dateroad/feign/discord/DiscordFeignReq.java
Labels: feat, 성준

#225 [FEAT] 코스 조회 Cache 적용 구현 - #222
  dateroad-api/src/main/java/org/dateroad/config/RedisCacheConfig.java
  dateroad-api/src/main/java/org/dateroad/course/dto/request/CourseGetAllReq.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
Labels: feat, 기훈

#228 [FIX] 유저 사진 Update 메소드 및 코스 당일 생성 에러 수정 - #227
  dateroad-api/src/main/java/org/dateroad/course/dto/request/CourseCreateReq.java
  dateroad-api/src/main/java/org/dateroad/user/service/UserService.java
Labels: fix, 기훈

#230 [FIX] Course Image 순서 변경 - #229
  dateroad-api/src/main/java/org/dateroad/image/service/ImageService.java
Labels: fix, 정원

#232 [fix] 프로필 수정 api 이미지 관련 변경 - #231
  dateroad-api/src/main/java/org/dateroad/user/service/UserService.java
Labels: fix, 성준

#234 [FEAT] 단일 Redis -> Cluster Migration - #233
  dateroad-api/src/main/java/org/dateroad/config/RedisCacheConfig.java
  dateroad-api/src/main/java/org/dateroad/config/RedisConfig.java
  dateroad-api/src/main/java/org/dateroad/config/RedisStreamConfig.java
  dateroad-api/src/main/java/org/dateroad/course/service/AsyncService.java
Labels: feat, refactor, 기훈
