Repository TeamDATEROAD/DATEROAD-SERVER, pull requests merged in 2024-10, with the labels that each got.

#293 [FEAT] 서버 에러 로그 Discord 연결 - #226
  dateroad-api/src/main/java/org/dateroad/user/service/AuthService.java
  dateroad-api/src/main/resources/console-appender.xml
  dateroad-api/src/main/resources/discord-appender.xml
  dateroad-api/src/main/resources/logback-spring.xml
  dateroad-api/src/test/java/org/dateroad/user/service/AuthServiceTest.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
  dateroad-common/src/main/java/org/dateroad/event/SignUpEventInfo.java
  dateroad-common/src/main/java/org/dateroad/mdc/MDCFilter.java
  dateroad-common/src/main/java/org/dateroad/mdc/MDCFilterConfig.java
  dateroad-common/src/main/java/org/dateroad/mdc/MDCManager.java
  dateroad-common/src/main/java/org/dateroad/mdc/RequestBodyWrapper.java
  dateroad-common/src/main/java/org/dateroad/mdc/RequestWrappingFilter.java
  dateroad-external/src/main/java/org/dateroad/feign/discord/DiscordLogAppender.java
Labels: feat, 정원

#295 [RELEASE] v1.0.2 릴리즈 - #294
  dateroad-api/src/main/java/org/dateroad/user/service/AuthService.java
  dateroad-api/src/main/resources/console-appender.xml
  dateroad-api/src/main/resources/discord-appender.xml
  dateroad-api/src/main/resources/logback-spring.xml
  dateroad-api/src/test/java/org/dateroad/user/service/AuthServiceTest.java
  dateroad-common/src/main/java/org/dateroad/code/FailureCode.java
  dateroad-common/src/main/java/org/dateroad/event/SignUpEventInfo.java
  dateroad-common/src/main/java/org/dateroad/mdc/MDCFilter.java
  dateroad-common/src/main/java/org/dateroad/mdc/MDCFilterConfig.java
  dateroad-common/src/main/java/org/dateroad/mdc/MDCManager.java
  dateroad-common/src/main/java/org/dateroad/mdc/RequestBodyWrapper.java
  dateroad-common/src/main/java/org/dateroad/mdc/RequestWrappingFilter.java
  dateroad-external/src/main/java/org/dateroad/feign/discord/DiscordLogAppender.java
Labels: release, 정원

#297 [ FIX] Multipart 요청 시 Filter 오류 해결 - #296
  dateroad-common/src/main/java/org/dateroad/mdc/RequestBodyWrapper.java
Labels: fix, 정원

#299 [RELEASE] v1.0.3 릴리즈 - #298
  dateroad-common/src/main/java/org/dateroad/mdc/RequestBodyWrapper.java
Labels: fix, release, 정원

#303 [FEAT] CORS 및 HTTPS 등록
  README.md
  dateroad-api/src/main/java/org/dateroad/auth/config/SecurityConfig.java
  dateroad-api/src/main/java/org/dateroad/config/SwaggerConfig.java
Labels: feat, release, 기훈

#306 [FEAT] Index 추가 - #305
  dateroad-domain/src/main/java/org/dateroad/date/domain/Course.java
  dateroad-domain/src/main/java/org/dateroad/date/domain/Date.java
  dateroad-domain/src/main/java/org/dateroad/date/repository/CourseRepository.java
  dateroad-domain/src/main/java/org/dateroad/image/domain/Image.java
  dateroad-domain/src/main/java/org/dateroad/like/domain/Like.java
  dateroad-domain/src/main/java/org/dateroad/place/domain/CoursePlace.java
Labels: feat, 기훈, beautiful

#312 [FEAT] Date 생성 시 date defualt 값 구현 - #311
  dateroad-api/src/main/java/org/dateroad/config/SwaggerConfig.java
  dateroad-api/src/main/java/org/dateroad/date/dto/request/DateCreateReq.java
Labels: feat, 정원

#314 [RELEASE] v1.0.4 릴리즈
  dateroad-api/src/main/java/org/dateroad/config/RedisStreamSubscriber.java
  dateroad-api/src/main/java/org/dateroad/config/SwaggerConfig.java
  dateroad-api/src/main/java/org/dateroad/course/api/CourseApi.java
  dateroad-api/src/main/java/org/dateroad/course/api/CourseController.java
  dateroad-api/src/main/java/org/dateroad/course/dto/CourseWithPlacesAndTagsDto.java
  dateroad-api/src/main/java/org/dateroad/course/service/AsyncService.java
  dateroad-api/src/main/java/org/dateroad/course/service/CoursePlaceService.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseRollbackService.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseTagService.java
  dateroad-api/src/main/java/org/dateroad/date/dto/request/DateCreateReq.java
  dateroad-api/src/main/java/org/dateroad/image/service/ImageService.java
  dateroad-api/src/main/java/org/dateroad/point/event/MessageDto.java
  dateroad-api/src/main/java/org/dateroad/point/event/PointEventListener.java
  dateroad-domain/src/main/java/org/dateroad/date/domain/Course.java
  dateroad-domain/src/main/java/org/dateroad/date/domain/Date.java
  dateroad-domain/src/main/java/org/dateroad/date/repository/CourseRepository.java
  dateroad-domain/src/main/java/org/dateroad/image/domain/Image.java
  dateroad-domain/src/main/java/org/dateroad/like/domain/Like.java
  dateroad-domain/src/main/java/org/dateroad/place/domain/CoursePlace.java
Labels: feat, refactor, release, 정원, 성준, 기훈
