Repository TeamDATEROAD/DATEROAD-SERVER, pull requests merged in 2025-03, with the labels that each got.

#322 [SETTING] Flyway 도입 및 초기 설정 - #321
  build.gradle
  dateroad-api/src/main/java/org/dateroad/user/facade/AuthFacade.java
  dateroad-common/build.gradle
Labels: setting, 정원

#323 [SETTING] Flyway 도입 및 초기 설정 배포
  .github/ISSUE_TEMPLATE/feature-request.md
  build.gradle
  dateroad-api/src/main/java/org/dateroad/user/facade/AuthFacade.java
  dateroad-common/build.gradle
Labels: release, 정원

#340 [FEAT] admin기능 추가해요
  dateroad-api/src/main/java/org/dateroad/admin/api/AdminController.java
  dateroad-api/src/main/java/org/dateroad/admin/dto/CourseFilterReq.java
  dateroad-api/src/main/java/org/dateroad/admin/service/AdminService.java
  dateroad-domain/src/main/java/org/dateroad/user/repository/UserRepository.java
Labels: feat, chore

#345 [FEAT] 포인트 생성 API
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-api/src/main/java/org/dateroad/point/api/PointController.java
  dateroad-api/src/main/java/org/dateroad/point/service/PointService.java
  dateroad-api/src/test/java/org/dateroad/point/service/PointServiceTest.java
Labels: feat, test, 정원

#347 [FIX] 캐시로 인한 User TotalPoint 에러 해결 - #346
  dateroad-api/src/main/java/org/dateroad/point/api/PointApi.java
  dateroad-api/src/main/java/org/dateroad/point/service/PointService.java
Labels: fix, docs, 정원

#348 [FEAT] Place Field 추가 및 Course 생성, 세부 조회 API 구현
  dateroad-api/src/main/java/org/dateroad/course/api/CourseControllerV2.java
  dateroad-api/src/main/java/org/dateroad/course/dto/request/CourseCreateEventV2.java
  dateroad-api/src/main/java/org/dateroad/course/dto/request/CoursePlaceGetReqV2.java
  dateroad-api/src/main/java/org/dateroad/course/service/AsyncService.java
  dateroad-api/src/main/java/org/dateroad/course/service/CoursePlaceService.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/CourseGetDetailResV2.java
  dateroad-domain/src/main/java/org/dateroad/place/domain/CoursePlace.java
  dateroad-domain/src/main/java/org/dateroad/place/domain/Place.java
Labels: feat, 정원

#349 [RELEASE] 릴리즈
  dateroad-api/src/main/java/org/dateroad/course/api/CourseControllerV2.java
  dateroad-api/src/main/java/org/dateroad/course/dto/request/CourseCreateEventV2.java
  dateroad-api/src/main/java/org/dateroad/course/dto/request/CoursePlaceGetReqV2.java
  dateroad-api/src/main/java/org/dateroad/course/service/AsyncService.java
  dateroad-api/src/main/java/org/dateroad/course/service/CoursePlaceService.java
  dateroad-api/src/main/java/org/dateroad/course/service/CourseService.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/CourseGetDetailResV2.java
  dateroad-api/src/main/java/org/dateroad/point/api/PointApi.java
  dateroad-api/src/main/java/org/dateroad/point/api/PointController.java
  dateroad-api/src/main/java/org/dateroad/point/service/PointService.java
  dateroad-api/src/test/java/org/dateroad/point/service/PointServiceTest.java
  dateroad-domain/src/main/java/org/dateroad/place/domain/CoursePlace.java
  dateroad-domain/src/main/java/org/dateroad/place/domain/Place.java
Labels: fix, feat, release

#351 [FEAT] Date Address Field 관련 Date 생성, 세부 조회 API - #350
  dateroad-api/src/main/java/org/dateroad/course/api/CourseApiV2.java
  dateroad-api/src/main/java/org/dateroad/course/api/CourseControllerV2.java
  dateroad-api/src/main/java/org/dateroad/date/api/DateApi.java
  dateroad-api/src/main/java/org/dateroad/date/api/DateApiV2.java
  dateroad-api/src/main/java/org/dateroad/date/api/DateControllerV2.java
  dateroad-api/src/main/java/org/dateroad/date/dto/request/DateCreateReqV2.java
  dateroad-api/src/main/java/org/dateroad/date/dto/request/PlaceCreateReqV2.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/DateDetailResV2.java
  dateroad-api/src/main/java/org/dateroad/date/dto/response/PlaceGetResV2.java
  dateroad-api/src/main/java/org/dateroad/date/service/DateService.java
  dateroad-domain/src/main/java/org/dateroad/place/domain/DatePlace.java
Labels: docs, feat
